name: 'Publish website'

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          repository: 'gircore/gir.core'
          ref: 'develop'
          path: 'src'
          submodules: 'true'

      - name: Prepare .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Run release build
        run: dotnet run -- --release --xml-documentation --targets docs
        working-directory: './src/Build'